name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag  secrets.IMAGE_NAME:0.0
    - name: Push the Docker image to Docker Hub
      run: docker push my-image-name:$(date +%s)
    - name: Logout from Docker Hub
      run: docker logout
