name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Docker Hub
      env:
        DOCKER_PASSWORD_FILE: ${{ github.workspace }}/docker_password
      run: echo ${{ secrets.DOCKER_PASSWORD }} > $DOCKER_PASSWORD_FILE && docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin < $DOCKER_PASSWORD_FILE
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Push the Docker image to Docker Hub
      run: docker push my-image-name:$(date +%s)
    - name: Logout from Docker Hub
      run: docker logout
    - name: Remove Docker password file
      run: rm $DOCKER_PASSWORD_FILE
